- src/app/mocks/services/parts-mock/parts.handler.ts
- src/app/modules/shared/modules/relations/core/relations.facade.ts
Because we changed how parts are loaded (with a queue), the fallback check was broken.
What happens when a part does not exist in the BE?
Here i do a check after we receive the list of IDs and add blank items for IDs that where not returned.
> TRACEFOSS-1110: removed bug with infinit loading animation on parts tree

- backend/src/test/java/org/eclipse/tractusx/traceability/investigations/domain/model/InvestigationReceiverTest.java
- docs/src/docs/administration/backend-configuration.adoc
- docs/src/docs/administration/frontend-configuration.adoc
- docs/src/docs/administration/installation.adoc
- changed links from ...catenax_ng... to ...eclipse-tractusx...
- corrected parts where tracefoss front- and backend parts were separated (after merge it needed to be done)
- Added Unit tests
> chore(documentation):[TRACEFOSS-XXX] changed links to tractusx, corrected doc after merge of tracefoss front- and backend

- .github/workflows/e2e-tests-xray_frontend.yml
- CHANGELOG.md
Handling this one:
https://github.com/eclipse-tractusx/traceability-foss/pull/144
> chore: TRACEFOSS-XXX bump cypress-io/github-action from 5.7.1 to 5.8.0

- tx-backend/src/integration/groovy/org/eclipse/tractusx/traceability/qualitynotification/alert/rest/PublisherAlertsControllerIT.groovy
- tx-backend/src/main/java/org/eclipse/tractusx/traceability/qualitynotification/domain/service/NotificationPublisherService.java
we currently create quality notifications for each asset in alert. 
this changes it to create one qualityNotification with affected assetIds.
> fix: TRACEFOSS-600 one alert in receiver side

- CHANGELOG.md
- frontend/package.json
- frontend/yarn.lock
The frontend is working, and the assets are available
> chore: [TRACEFOSS-XXX] Bump postcss from 8.4.23 to 8.4.31

- frontend/yarn.lock
The frontend is working, and the assets are available
> chore: [TRACEFOSS-XXX] bump word-wrap from 1.2.3 to 1.2.5 in/frontend

- tx-backend/src/main/java/org/eclipse/tractusx/traceability/common/request/SearchCriteriaRequestParam.java
resolves eclipse-tractusx/traceability-foss#392
> bug: 392 limit filter param to 1100 characters

- tx-backend/src/main/java/org/eclipse/tractusx/traceability/assets/infrastructure/asbuilt/repository/AssetAsBuiltRepositoryImpl.java
- tx-backend/src/main/java/org/eclipse/tractusx/traceability/assets/infrastructure/asplanned/repository/AssetAsPlannedRepositoryImpl.java
- tx-backend/src/test/java/org/eclipse/tractusx/traceability/integration/importdata/ImportControllerIT.java
- tx-backend/src/test/resources/testdata/importfiles/validImportFile-onlyAsBuiltAsset.json
- tx-backend/src/test/resources/testdata/importfiles/validImportFile-onlyAsPlannedAsset.json
resolves eclipse-tractusx/traceability-foss#546
> bug(tx-backend): #546 fix issue with one type of bom lifecycle in importfile

- COMPATIBILITY_MATRIX.md
References eclipse-tractusx/traceability-foss#540
> chore[540]: updated COMPATIBILITY_MATRIX.md

- CONTRIBUTING.md
Update CONTRIBUTING.md file adaptions to github for commit messages 
> Update CONTRIBUTING.md file adaptions to github

- charts/traceability-foss/values-dev.yaml
- charts/traceability-foss/values-e2e-a.yaml
- charts/traceability-foss/values-e2e-b.yaml
- charts/traceability-foss/values-int-a.yaml
- charts/traceability-foss/values-int-b.yaml
- charts/traceability-foss/values-test.yaml
resolves eclipse-tractusx/traceability-foss#552
> chore(deployment): 552 update app ids

- .github/workflows/docker-image-main_backend.yml
- .github/workflows/docker-image-main_frontend.yml
- .github/workflows/docker-image-tag-release.yaml
- CHANGELOG.md
- DOCKER_NOTICE.md
- README.md
- frontend/DOCKER_NOTICE.md
resolves eclipse-tractusx/traceability-foss#681
> chore(documentation): 681 TRG 4.06 separate Docker Notice

- CHANGELOG.md
- frontend/src/app/modules/shared/components/table/table.component.html
resolves eclipse-tractusx/traceability-foss#528
> chore(bug): 528 disabled sorting tooltip on dashboard tables

- CHANGELOG.md
- docs/src/docs/arc42/cross-cutting/domain-concepts.adoc
- docs/src/uml-diagrams/arc42/cross-cutting/domain-model/domain-model-quality-notifications.puml
- docs/src/uml-diagrams/arc42/cross-cutting/domain-model/domain-model.puml
- tx-backend/openapi/traceability-foss-backend.json
- tx-backend/src/main/java/org/eclipse/tractusx/traceability/qualitynotification/application/alert/mapper/AlertResponseMapper.java
- tx-backend/src/main/java/org/eclipse/tractusx/traceability/qualitynotification/application/base/mapper/QualityNotificationMapper.java
- tx-backend/src/main/java/org/eclipse/tractusx/traceability/qualitynotification/application/investigation/mapper/InvestigationResponseMapper.java
- tx-backend/src/main/java/org/eclipse/tractusx/traceability/qualitynotification/domain/base/model/QualityNotification.java
- tx-backend/src/main/java/org/eclipse/tractusx/traceability/qualitynotification/infrastructure/alert/model/AlertEntity.java
- tx-backend/src/main/java/org/eclipse/tractusx/traceability/qualitynotification/infrastructure/investigation/model/InvestigationEntity.java
- tx-backend/src/main/java/org/eclipse/tractusx/traceability/qualitynotification/infrastructure/model/NotificationBaseEntity.java
- tx-backend/src/main/resources/db/migration/V16__move_errormessage_to_notifications.sql
- tx-backend/src/test/java/org/eclipse/tractusx/traceability/integration/qualitynotification/investigation/ReadInvestigationsControllerIT.java
- tx-models/src/main/java/qualitynotification/base/response/QualityNotificationMessageResponse.java
- tx-models/src/main/java/qualitynotification/base/response/QualityNotificationResponse.java
resolves eclipse-tractusx/traceability-foss#423
> feat(notifications): 423 - Adding notification list to response

- docs/RELEASE.md
> chore: add irs-edc-lib to release flow to avoid snapshots

- tx-backend/src/main/java/org/eclipse/tractusx/traceability/contracts/application/rest/ContractController.java
resolves eclipse-tractusx/traceability-foss#420
> feature: 420 refactor swagger

- frontend/src/app/modules/shared/components/table/table.component.html
resolves eclipse-tractusx/traceability-foss#421
> chore(contracts): 421 remove tooltip on unsortable table columns

- CHANGELOG.md
- tx-backend/src/main/java/org/eclipse/tractusx/traceability/contracts/application/mapper/ContractFieldMapper.java
resolves eclipse-tractusx/traceability-foss#736
> feature: #736 add contractAgreementId as searchable field for /contracts

- CHANGELOG.md
- tx-backend/src/main/java/org/eclipse/tractusx/traceability/shelldescriptor/domain/service/DecentralRegistryServiceImpl.java
- tx-backend/testdata/CX_Testdata_MessagingTest_v0.0.12.json
- tx-backend/testdata/CX_Testdata_MessagingTest_v0.0.13.json
resolves eclipse-tractusx/traceability-foss#602
> feature: #602 use digitalTwinType instead of semanticId

- frontend/src/app/modules/shared/components/request-notification-new/notification-new-request.component.ts
resolves eclipse-tractusx/traceability-foss#783
> chore(helm):783 fixxed environment import

- CHANGELOG.md
- Dockerfile
- tx-backend/src/main/java/org/eclipse/tractusx/traceability/assets/application/importpoc/validation/JsonFileValidator.java
- tx-backend/src/main/java/org/eclipse/tractusx/traceability/assets/domain/importpoc/service/DtrService.java
resolves eclipse-tractusx/traceability-foss#837
> chore(exception):837 fix import.

- tx-backend/src/main/java/org/eclipse/tractusx/traceability/notification/domain/base/service/NotificationsEDCFacade.java
- tx-backend/testdata/CX_Testdata_MessagingTest_v0.0.13.json
resolves eclipse-tractusx/traceability-foss#978
> bug: #978 update testdata

- DEPENDENCIES_BACKEND
> Update Dependencies Backend Action
