catenax-ng/tx-traceability-foss

- src/app/modules/core/api/api.interceptor.ts
> fix: added check that compares response and request url

- scripts/inject-dynamic-env.js
> fix: add CATENAX_PORTAL_URL to inject-dynamic-env.js

- src/assets/locales/de/page.error-page.json
> fix: fixed missing translation for error page

- frontend/src/app/mocks/services/investigations-mock/investigations.model.ts
- frontend/src/app/mocks/services/investigations-mock/investigations.test.model.ts
- frontend/src/app/modules/page/dashboard/presentation/dashboard.component.html
- frontend/src/app/modules/page/investigations/presentation/investigations.component.html
- frontend/src/app/modules/page/parts/model/parts.model.ts
- frontend/src/app/modules/shared/assembler/investigations.assembler.spec.ts
- frontend/src/app/modules/shared/assembler/investigations.assembler.ts
- frontend/src/app/modules/shared/components/notification-overview/notification-overview.component.html
- frontend/src/app/modules/shared/components/request-investigation/request-investigation.component.html
- frontend/src/app/modules/shared/components/request-investigation/request-investigation.component.ts
- frontend/src/app/modules/shared/components/severity-select/severity-select.component.html
- frontend/src/app/modules/shared/components/severity-select/severity-select.component.spec.ts
- frontend/src/app/modules/shared/components/severity-select/severity-select.component.ts
- frontend/src/app/modules/shared/components/severity/severity.component.html
- frontend/src/app/modules/shared/components/severity/severity.component.scss
- frontend/src/app/modules/shared/components/severity/severity.component.spec.ts
- frontend/src/app/modules/shared/components/severity/severity.component.ts
- frontend/src/app/modules/shared/model/notification.model.ts
- frontend/src/app/modules/shared/model/severity.model.ts
- frontend/src/app/modules/shared/modules/notification/modal/modalTestHelper.spec.ts
- frontend/src/app/modules/shared/modules/notification/notification-tab/notification-tab.component.html
- frontend/src/app/modules/shared/modules/notification/notification-tab/notification-tab.component.ts
- frontend/src/app/modules/shared/modules/notification/presentation/notification.component.ts
- frontend/src/app/modules/shared/service/investigations.service.ts
- frontend/src/app/modules/shared/shared.module.ts
- frontend/src/assets/locales/de/common.json
- frontend/src/assets/locales/en/common.json
- frontend/src/theme/base.scss
- frontend/tailwind.config.js
- frontend/yarn.lock
> feature: [FE] User select severity for Quality Investigation

- backend/src/main/java/org/eclipse/tractusx/traceability/investigations/domain/model/Investigation.java
feature(fix): TRACEFOSS-936 Adapt behaviour to also include the reason of notifications
> feature(fix): TRACEFOSS-936 Adapt behaviour to also include the reason of notifications

- .github/workflows/pull-request-backend.yml
- .github/workflows/sonar-scan-backend.yml
- .github/workflows/unit-test_frontend.yml
What are in the Vault defined are not the same with the SonarCloud
> TRACEFOXX-1029-Update-Sonar-Keys

- .github/workflows/docker-image-tag-release.yaml
- backend/pom.xml
Currently frontend does not build an fe_latest image on release.
> fix: TRACEFOSS-1029 Add fe_latest image tag to release step

- .github/workflows/xray-cucumber.yaml
- backend/cucumber-tests/pom.xml
- backend/cucumber-tests/src/test/java/org/eclipse/tractusx/traceability/RunCucumberTest.java
- backend/cucumber-tests/src/test/java/org/eclipse/tractusx/traceability/TestStepDefinition.java
- backend/cucumber-tests/src/test/resources/features/1_TRACEFOSS-1282.feature
Enable Export of Cucumber Tests from Xray/JIRA
Cucumber execution 
Reimport of report to test execution
> chore(cicd):[TRACEFOSS-719] enable cucumber execution via xray

- CHANGELOG.md
- frontend/src/app/modules/page/parts/presentation/parts.component.html
- frontend/src/app/modules/page/parts/presentation/parts.component.ts
- frontend/src/app/modules/shared/assembler/parts.assembler.spec.ts
- frontend/src/app/modules/shared/assembler/parts.assembler.ts
removed quality type from ui but kept base functionality
> feature: TRACEFOSS-1226 - removed quality type

- CHANGELOG.md
- frontend/cypress/support/step_definitions/dashboard.ts
- frontend/src/app/modules/shared/components/table/table.component.html
- frontend/src/app/modules/shared/components/table/table.component.scss
- frontend/src/app/modules/shared/components/table/table.component.ts
- frontend/src/assets/locales/de/common.json
- frontend/src/assets/locales/en/common.json
fixed table selecton and improved usability of multiselect
> feature: TRACEFOSS-872 - fixed table selecton

- .github/workflows/publish-documentation.yaml
No Changelog provision since this is an addition to PR [TRI-1402](https://github.com/catenax-ng/tx-traceability-foss/pull/234)
> chore(testdata):[TRACEFOSS-1402] add user-guide to publish documentation

- docs/src/uml-diagrams/concept/TRACEFOSS-1423/domain-model.puml
> chore(uml):[TRACEFOSS-1423] add domain model

- CHANGELOG.md
- frontend/yarn.lock
https://github.com/catenax-ng/tx-traceability-foss/security/dependabot/12
> chore: TRACEFOSS-XXXX Upgrade karma package dependency: socket.io-parser to 4.2.3

- CHANGELOG.md
- frontend/src/app/modules/shared/components/card-list/card-list.component.scss
…n section "Overview" in quality investigation detail page
> fix: TRACEFOSS-1280 Correct alignment for severity and other fields in section "Overview" in quality investigation detail page

- CHANGELOG.md
- DEPENDENCIES_BACKEND
- pom.xml
Update spring boot to fix cve.
> Chore/tracefoss 1562 fix autoconfigure springboot CVE

- tx-backend/src/main/resources/application-int-a.yml
- tx-backend/src/main/resources/application-int-b.yml
int-a and int-b require different cors configuration than provided in the application.yaml
> feature: TRACEFOSS-1526 configuration for cors

- tx-backend/src/main/java/org/eclipse/tractusx/traceability/infrastructure/edc/blackbox/InvestigationsEDCFacade.java
- tx-backend/src/test/java/org/eclipse/tractusx/traceability/infrastructure/edc/blackbox/EdcServiceTest.java
- tx-backend/src/test/java/org/eclipse/tractusx/traceability/infrastructure/edc/blackbox/InvestigationsEDCFacadeTest.java
- tx-backend/src/test/java/org/eclipse/tractusx/traceability/testdata/CatalogTestDataFactory.java
- tx-backend/src/test/java/org/eclipse/tractusx/traceability/testdata/NotificationTestDataFactory.java
Add unit tests to InvestigationsEDCFacade
> chore: increase code coverage

- CHANGELOG.md
- tx-backend/src/main/java/org/eclipse/tractusx/traceability/assets/infrastructure/base/irs/model/response/JobDetailResponse.java
- tx-backend/src/main/resources/data/irs_job_response_with_null_manufacturer_names.json
- tx-backend/src/test/java/org/eclipse/tractusx/traceability/assets/infrastructure/repository/rest/irs/model/JobDetailResponseTest.java
> fix: TRACEFOSS-2394 issue with manufacturerName null on release branch

- CHANGELOG.md
- tx-backend/src/main/java/org/eclipse/tractusx/traceability/assets/infrastructure/base/irs/model/response/JobDetailResponse.java
- tx-backend/src/main/resources/data/irs_job_response_with_null_manufacturer_names.json
- tx-backend/src/test/java/org/eclipse/tractusx/traceability/assets/infrastructure/repository/rest/irs/model/JobDetailResponseTest.java
> fix: TRACEFOSS-2394 issue with manufacturerName null on main branch

- SECURITY.md
SECURITY FILE
The security file contain the information, where/how to report a vulnerability issue. See the [Handbook#vulnerability](https://www.eclipse.org/projects/handbook/#vulnerability) and this [example](https://github.com/eclipse-tractusx/eclipse-tractusx.github.io/blob/main/SECURITY.md).
Please ensure to do as many of the following checks as possible, before asking for committer review:
> fix(security):[TRACEFOSS-2623]  [QG4] TRG 7.0.1 - Legal Document Update

- tx-backend/src/main/java/org/eclipse/tractusx/traceability/assets/application/asbuilt/mapper/AssetAsBuiltResponseMapper.java
- tx-backend/src/main/java/org/eclipse/tractusx/traceability/assets/application/asplanned/mapper/AssetAsPlannedResponseMapper.java
- tx-backend/src/main/java/org/eclipse/tractusx/traceability/assets/application/base/mapper/AssetBaseResponseMapper.java
- tx-backend/src/main/java/org/eclipse/tractusx/traceability/assets/domain/base/model/AssetBase.java
- tx-backend/src/main/java/org/eclipse/tractusx/traceability/assets/infrastructure/asbuilt/model/AssetAsBuiltEntity.java
- tx-backend/src/main/java/org/eclipse/tractusx/traceability/assets/infrastructure/asplanned/model/AssetAsPlannedEntity.java
- tx-backend/src/main/java/org/eclipse/tractusx/traceability/common/config/ApplicationProfiles.java
- tx-backend/src/main/java/org/eclipse/tractusx/traceability/common/config/ApplicationStartupConfig.java
- tx-backend/src/main/java/org/eclipse/tractusx/traceability/common/config/SchedulerConfig.java
- tx-backend/src/main/java/org/eclipse/tractusx/traceability/infrastructure/edc/properties/EdcProperties.java
- tx-backend/src/main/java/org/eclipse/tractusx/traceability/qualitynotification/domain/base/model/QualityNotification.java
- tx-backend/src/main/java/org/eclipse/tractusx/traceability/qualitynotification/domain/base/model/QualityNotificationStatus.java
- tx-backend/src/main/java/org/eclipse/tractusx/traceability/qualitynotification/infrastructure/investigation/model/InvestigationEntity.java
- tx-backend/src/test/java/org/eclipse/tractusx/traceability/common/config/ApplicationStartupConfigTest.java
- tx-backend/src/test/java/org/eclipse/tractusx/traceability/integration/assets/AssetAsBuiltControllerByIdIT.java
- tx-backend/src/test/java/org/eclipse/tractusx/traceability/integration/assets/AssetAsPlannedControllerByIdIT.java
- tx-backend/src/test/java/org/eclipse/tractusx/traceability/integration/assets/DashboardControllerIT.java
- tx-backend/src/test/java/org/eclipse/tractusx/traceability/integration/common/support/AlertsSupport.java
- tx-backend/src/test/java/org/eclipse/tractusx/traceability/integration/common/support/InvestigationsSupport.java
- tx-backend/src/test/java/org/eclipse/tractusx/traceability/integration/qualitynotification/alert/AlertsRepositoryIT.java
- tx-models/src/main/java/assets/response/base/AssetBaseResponse.java
> TRACEFOSS-2537 alerts and investigations count on asset response

- tx-backend/src/integration/groovy/org/eclipse/tractusx/traceability/common/config/RestAssuredConfig.groovy
- tx-backend/src/main/java/org/eclipse/tractusx/traceability/common/config/ApplicationProfiles.java
- tx-backend/src/main/java/org/eclipse/tractusx/traceability/common/config/ErrorHandlingConfig.java
- tx-backend/src/main/java/org/eclipse/tractusx/traceability/common/config/SecurityConfig.java
- tx-backend/src/main/java/org/eclipse/tractusx/traceability/submodel/application/rest/SubmodelController.java
- tx-backend/src/main/java/org/eclipse/tractusx/traceability/submodel/application/service/SubmodelService.java
- tx-backend/src/main/java/org/eclipse/tractusx/traceability/submodel/domain/model/Submodel.java
- tx-backend/src/main/java/org/eclipse/tractusx/traceability/submodel/domain/model/SubmodelNotFoundException.java
- tx-backend/src/main/java/org/eclipse/tractusx/traceability/submodel/domain/repository/SubmodelRepository.java
- tx-backend/src/main/java/org/eclipse/tractusx/traceability/submodel/domain/service/SubmodelServiceImpl.java
- tx-backend/src/main/java/org/eclipse/tractusx/traceability/submodel/infrastructure/SubmodelEntity.java
- tx-backend/src/main/java/org/eclipse/tractusx/traceability/submodel/infrastructure/model/SubmodelEntity.java
- tx-backend/src/main/java/org/eclipse/tractusx/traceability/submodel/infrastructure/reposotory/JpaSubmodelRepository.java
- tx-backend/src/main/java/org/eclipse/tractusx/traceability/submodel/infrastructure/reposotory/SubmodelRepositoryImpl.java
- tx-backend/src/main/resources/application-integration-spring-boot.yml
- tx-backend/src/main/resources/db/migration/V29__submodel_entity.sql
- tx-backend/src/test/java/org/eclipse/tractusx/traceability/integration/IntegrationTestSpecification.java
- tx-backend/src/test/java/org/eclipse/tractusx/traceability/integration/RestAssuredConfig.java
- tx-backend/src/test/java/org/eclipse/tractusx/traceability/integration/submodel/SubmodelControllerIT.java
Since Stable environment does not support submodelserver chart we had to implement support API to maintain asset providing functionality through EDC provider
> feature: TRACEFOSS-2696 RELEASE submodelserver api

- CHANGELOG.md
- frontend/package.json
- frontend/scripts/replace-base-href.js
deployed on dev, build output is hashed. With that I suppose it will work.
> feature(cache):[TRACEFOSS-XXX] added cache busting

- charts/traceability-foss/values-int-basf.yaml
- charts/traceability-foss/values-int-bmw.yaml
> chore(deployment): TRACEFOSS-XXXX

- docs/src/docs/arc42/trace-x-data-import-interface/data-import-interface.adoc
- docs/src/uml-diagrams/arc42/trace-x-data-import-interface/trace-x-data-import-interface-modul2-sequence.puml
- docs/src/uml-diagrams/arc42/trace-x-data-import-interface/trace-x-data-import-interface-modul2-swimlane.puml
- docs/src/uml-diagrams/arc42/trace-x-data-import-interface/trace-x-data-import-interface-modul3-sequence.puml
- docs/src/uml-diagrams/arc42/trace-x-data-import-interface/trace-x-data-import-interface-modul3-swimlane.puml
Hi @ds-mwesener ,
take a look at this please. There was a swimlane option in puml. I also added a sequence diagram, let me know which one you prefer. :) 
I doublechecked with Martin if I should do it in PUML or Mermaid.  His answer was PUML.
Regards,
Janice
> chore(): [TRACEFOSS-XXX] added diagrams for tracex dataimport

- tx-backend/src/main/java/org/eclipse/tractusx/traceability/common/request/PageableFilterRequest.java
- tx-backend/src/main/java/org/eclipse/tractusx/traceability/common/request/SearchCriteriaRequestParam.java
- tx-backend/src/test/java/org/eclipse/tractusx/traceability/integration/qualitynotification/alert/AlertControllerFilterIT.java
resolves eclipse-tractusx/traceability-foss#392
> bug: 392 fix http 400 response of filter parameter

- charts/traceability-foss/Chart.yaml
- charts/traceability-foss/values-base.yaml
- charts/traceability-foss/values-dev.yaml
- charts/traceability-foss/values-e2e-a.yaml
- charts/traceability-foss/values-e2e-b.yaml
- charts/traceability-foss/values-int-a.yaml
- charts/traceability-foss/values-int-b.yaml
- charts/traceability-foss/values-int-basf.yaml
- charts/traceability-foss/values-int-bmw.yaml
- charts/traceability-foss/values-test.yaml
> ENVIRONMENT: updated irs 

- tx-backend/src/main/java/org/eclipse/tractusx/traceability/common/config/ErrorHandlingConfig.java
- tx-backend/src/main/java/org/eclipse/tractusx/traceability/common/request/OwnPageable.java
- tx-backend/src/main/java/org/eclipse/tractusx/traceability/common/request/SearchCriteriaRequestParam.java
- tx-backend/src/main/java/org/eclipse/tractusx/traceability/common/request/exception/InvalidFilterException.java
- tx-backend/src/main/java/org/eclipse/tractusx/traceability/common/request/exception/InvalidSortException.java
- tx-backend/src/test/java/org/eclipse/tractusx/traceability/integration/qualitynotification/alert/AlertControllerFilterIT.java
resolves eclipse-tractusx/traceability-foss#546
> bug(tx-backend): #546 fix main branch test

- CHANGELOG.md
- pom.xml
- tx-backend/pom.xml
- tx-backend/src/main/java/org/eclipse/tractusx/traceability/assets/application/ImportController.java
- tx-backend/src/main/java/org/eclipse/tractusx/traceability/assets/application/importpoc/validation/JsonFileValidator.java
- tx-backend/src/main/java/org/eclipse/tractusx/traceability/assets/application/importpoc/validation/exception/JsonFileProcessingException.java
- tx-backend/src/main/java/org/eclipse/tractusx/traceability/assets/application/importpoc/validation/exception/NotSupportedSchemaException.java
- tx-backend/src/main/java/org/eclipse/tractusx/traceability/common/config/ErrorHandlingConfig.java
- tx-backend/src/main/resources/validation/PartSiteInformationAsPlanned_1.0.0-schema.json
- tx-backend/src/test/java/org/eclipse/tractusx/traceability/common/config/ErrorHandlingConfigTest.java
- tx-backend/src/test/java/org/eclipse/tractusx/traceability/integration/importdata/ImportControllerIT.java
- tx-backend/src/test/resources/testdata/importfiles/invalidImportFile.json
- tx-backend/src/test/resources/testdata/importfiles/validImportFile.json
- tx-backend/src/test/resources/testdata/importfiles/validImportFileButWrongBPN.json
- tx-backend/testdata/import-test-data-CML1_v0.0.12.json
- tx-backend/testdata/import-test-data-CNKC_v0.0.12.json
resolves eclipse-tractusx/traceability-foss#546
> chore(tx-backend): #546 exchange json validator library

- docs/concept/Concept_TEMPLATE.md
resolves eclipse-tractusx/traceability-foss#322
> chore(concept):[#322]Update Concept_TEMPLATE.md

- docs/concept/Concept_TEMPLATE.md
As requested by Johannes, I have added a note which explains that the implementation can differ from the concept.
> chore(docs): update of concept template.

- README.md
> Update README.md add contact information

- CHANGELOG.md
- CONTRIBUTING.md
> Update CONTRIBUTING.md add matrix chat

- tx-backend/src/main/java/org/eclipse/tractusx/traceability/assets/application/importpoc/rest/ImportController.java
- tx-backend/src/main/java/org/eclipse/tractusx/traceability/assets/domain/importpoc/service/PublishServiceImpl.java
- tx-models/src/main/java/assets/importpoc/ValidationResponse.java
resolves eclipse-tractusx/traceability-foss#534
> feature: 534 improve logging

- CHANGELOG.md
- charts/traceability-foss/CHANGELOG.md
> chore(release): 10.3.0

- frontend/src/app/modules/shared/service/parts.service.ts
Merge into hotfix and into main branch
> chore(security): XXX fix medium security findings from veracode (hotfix)

- CHANGELOG.md
- charts/traceability-foss/CHANGELOG.md
> chore(release): 10.4.0

- CHANGELOG.md
- docs/concept/#621-edit-parts-in-notifications/#621-edit-parts-in-notifications.md
> chore(concept): changed add parts concept to edit parts concept

- tx-backend/src/main/java/org/eclipse/tractusx/traceability/assets/infrastructure/asbuilt/repository/AssetAsBuiltRepositoryImpl.java
- tx-backend/src/main/java/org/eclipse/tractusx/traceability/assets/infrastructure/asplanned/repository/AssetAsPlannedRepositoryImpl.java
> bug: fix duplicate key value

- CHANGELOG.md
- frontend/src/app/modules/page/alerts/presentation/alerts.component.spec.ts
- frontend/src/app/modules/page/alerts/presentation/alerts.component.ts
- frontend/src/app/modules/page/investigations/presentation/investigations.component.spec.ts
- frontend/src/app/modules/page/investigations/presentation/investigations.component.ts
- frontend/src/app/modules/page/other-parts/presentation/customer-parts/customer-parts.component.spec.ts
- frontend/src/app/modules/page/other-parts/presentation/customer-parts/customer-parts.component.ts
- frontend/src/app/modules/page/other-parts/presentation/supplier-parts/supplier-parts.component.spec.ts
- frontend/src/app/modules/page/other-parts/presentation/supplier-parts/supplier-parts.component.ts
- frontend/src/app/modules/page/parts/presentation/parts.component.ts
- frontend/src/app/modules/shared/helper/table-helper.ts
resolves eclipse-tractusx/traceability-foss#438
> chore(bug): 438 enabling multisorting with meta key

- CHANGELOG.md
- docs/RELEASE.md
> chore(documentation): Update RELEASE.md documentation

- CHANGELOG.md
- frontend/src/app/modules/page/other-parts/presentation/customer-parts/customer-parts.component.html
- frontend/src/app/modules/page/other-parts/presentation/customer-parts/customer-parts.component.spec.ts
- frontend/src/app/modules/page/other-parts/presentation/customer-parts/customer-parts.component.ts
- frontend/src/app/modules/page/other-parts/presentation/supplier-parts/supplier-parts.component.spec.ts
- frontend/src/app/modules/page/other-parts/presentation/supplier-parts/supplier-parts.component.ts
- frontend/src/app/modules/shared/components/parts-table/parts-table.component.html
resolves eclipse-tractusx/traceability-foss#542
> chore(bug): 542 bugfix filter and sorting in other parts

- CHANGELOG.md
> add informartion to add issue number to changelog

- CHANGELOG.md
- frontend/src/app/modules/shared/components/toasts/toast-message/toast-message.component.html
- frontend/src/app/modules/shared/components/toasts/toast-message/toast-message.component.spec.ts
- frontend/src/app/modules/shared/components/toasts/toast-message/toast-message.component.ts
resolves eclipse-tractusx/traceability-foss#515
> chore(notifications): 515 fixed notification toast click area

- tx-backend/src/main/java/org/eclipse/tractusx/traceability/qualitynotification/application/alert/rest/AlertController.java
- tx-backend/src/main/java/org/eclipse/tractusx/traceability/qualitynotification/application/base/service/QualityNotificationService.java
- tx-backend/src/main/java/org/eclipse/tractusx/traceability/qualitynotification/application/contract/EdcNotificationContractController.java
- tx-backend/src/main/java/org/eclipse/tractusx/traceability/qualitynotification/application/investigation/rest/InvestigationsController.java
- tx-backend/src/main/java/org/eclipse/tractusx/traceability/qualitynotification/domain/alert/model/StartQualityNotification.java
- tx-backend/src/main/java/org/eclipse/tractusx/traceability/qualitynotification/domain/alert/service/AlertServiceImpl.java
- tx-backend/src/main/java/org/eclipse/tractusx/traceability/qualitynotification/domain/base/model/QualityNotification.java
- tx-backend/src/main/java/org/eclipse/tractusx/traceability/qualitynotification/domain/base/model/QualityNotificationSeverity.java
- tx-backend/src/main/java/org/eclipse/tractusx/traceability/qualitynotification/domain/base/model/QualityNotificationStatus.java
- tx-backend/src/main/java/org/eclipse/tractusx/traceability/qualitynotification/domain/investigation/service/InvestigationServiceImpl.java
- tx-backend/src/main/java/org/eclipse/tractusx/traceability/qualitynotification/infrastructure/investigation/repository/JpaInvestigationRepository.java
- tx-backend/src/main/java/org/eclipse/tractusx/traceability/qualitynotification/infrastructure/model/NotificationBaseEntity.java
- tx-backend/src/test/java/org/eclipse/tractusx/traceability/qualitynotification/application/alert/rest/AlertControllerTest.java
resolves eclipse-tractusx/traceability-foss#423
> feat(notifications): 423 - quality notification refactoring.

- COMPATIBILITY_MATRIX.md
> chore: update COMPATIBILITY_MATRIX.md

- CHANGELOG.md
- frontend/src/app/mocks/services/parts-mock/partsAsBuilt/partsAsBuilt.model.ts
- frontend/src/app/modules/page/parts/model/parts.model.ts
- frontend/src/app/modules/shared/components/chip/chip.component.scss
- frontend/src/assets/locales/de/common.json
- frontend/src/assets/locales/en/common.json
resolves eclipse-tractusx/traceability-foss#536
> chore(importstate): 536 added import state published to cx

- tx-backend/openapi/traceability-foss-backend.json
- tx-backend/src/main/java/org/eclipse/tractusx/traceability/contracts/application/rest/ContractController.java
- tx-models/src/main/java/assets/importpoc/ErrorResponse.java
resolves eclipse-tractusx/traceability-foss#420
> feature: 420 refactor swagger

- charts/stable/manifests/traceability-foss/argoCD-manifest-stable-a.yaml
- charts/stable/manifests/traceability-foss/argoCD-manifest-stable-b.yaml
- charts/traceability-foss/values-base.yaml
- charts/traceability-foss/values-dev.yaml
- charts/traceability-foss/values-e2e-a.yaml
- charts/traceability-foss/values-e2e-b.yaml
- charts/traceability-foss/values-int-a.yaml
- charts/traceability-foss/values-int-b.yaml
- charts/traceability-foss/values-int-basf.yaml
- charts/traceability-foss/values-int-bmw.yaml
- charts/traceability-foss/values-pen.yaml
- charts/traceability-foss/values-test.yaml
resolves eclipse-tractusx/traceability-foss#536
> feature(tx-backend): #536 add allowed BPNS to env configurations

- tx-backend/src/main/resources/db/migration/V17__set_30_chars_for_import_state.sql
resolves eclipse-tractusx/traceability-foss#536
> feature(tx-backend): #536 fix migration

- docs/src/docs/arc42/runtime-view/data-provisioning/publish-assets-error.adoc
- docs/src/docs/arc42/runtime-view/data-provisioning/publish-assets.adoc
- docs/src/docs/arc42/runtime-view/data-provisioning/return-import-report.adoc
- tx-backend/src/main/java/org/eclipse/tractusx/traceability/assets/domain/base/model/ImportNote.java
- tx-backend/src/main/java/org/eclipse/tractusx/traceability/assets/infrastructure/base/irs/IrsRepositoryImpl.java
> chore(tx-backend): fix documentation generation issues and import notes typos

- CHANGELOG.md
- DOCKER_NOTICE.md
- Dockerfile
> chore(tx-backend): base image bumps

- CHANGELOG.md
- pom.xml
> chore: update irs lib

- .github/workflows/pull-request_backend.yml
> chore: fix count of snapshot versions in root pom properties

- CHANGELOG.md
- charts/traceability-foss/CHANGELOG.md
> chore(release): 10.7.0

- COMPATIBILITY_MATRIX.md
> chore(documentation): add 10.7.0 compatibility matrix

- tx-backend/src/main/java/org/eclipse/tractusx/traceability/common/properties/EdcProperties.java
> chore(tx-backend) fix problem with EdcProperties

- frontend/cypress/integration/pages/AdminPage.ts
- frontend/cypress/support/step_definitions/admin-contracts.ts
> chore(e2e): fix failing tests

- tx-backend/src/main/java/org/eclipse/tractusx/traceability/qualitynotification/domain/contract/EdcNotificationContractService.java
resolves eclipse-tractusx/traceability-foss#596
> chore(bug): 596 - Fix if policy already exists

- tx-cucumber-tests/src/test/java/org/eclipse/tractusx/traceability/test/TraceabilityTestStepDefinition.java
- tx-cucumber-tests/src/test/java/org/eclipse/tractusx/traceability/test/tooling/NotificationTypeEnum.java
- tx-cucumber-tests/src/test/java/org/eclipse/tractusx/traceability/test/tooling/rest/RestProvider.java
resolves eclipse-tractusx/traceability-foss#706
> 706 cucumber tests adjustments merge only after other 706 MR

- docs/src/uml-diagrams/arc42/cross-cutting/erm-trace-x.puml
- tx-backend/src/main/resources/db/migration/V21__remove_notification_connection_from_as_planned.sql
- tx-backend/src/test/java/org/eclipse/tractusx/traceability/integration/common/support/DatabaseSupport.java
resolves eclipse-tractusx/traceability-foss#706
> chore(tx-backend) 706 erd diagram update and removal on unneeded tables

- .github/workflows/e2e-tests-xray_frontend.yml
- frontend/.gitignore
- frontend/cypress/support/step_definitions/login.ts
- frontend/package.json
- frontend/src/app/modules/core/known-route.ts
- frontend/src/app/modules/page/dashboard/presentation/dashboard.component.html
- frontend/src/app/modules/shared/model/notification.model.ts
resolves eclipse-tractusx/traceability-foss#616
> chore(feature): 616 - adapt changes for cypress.

- CHANGELOG.md
resolves eclipse-tractusx/traceability-foss#736
> feature: #736 update CHANGELOG.md

- frontend/TESTING.md
- frontend/package.json
- frontend/src/app/modules/page/dashboard/presentation/dashboard.component.html
- frontend/src/app/modules/page/dashboard/presentation/dashboard.component.ts
- frontend/src/app/modules/shared/components/request-notification/request-notification.component.ts
- frontend/src/app/modules/shared/components/toasts/toast-message/toast-message.component.html
- frontend/src/assets/locales/en/common.json
resolves eclipse-tractusx/traceability-foss#616
> chore(feature): 616 - adapt page index of inbox.

- docs/src/docs/arc42/runtime-view/policies.adoc
- docs/src/uml-diagrams/arc42/runtime-view/policies/policy-assets.puml
- docs/src/uml-diagrams/arc42/runtime-view/policies/policy-notifications.puml
- docs/src/uml-diagrams/arc42/runtime-view/policies/policy-startup-configuration.puml
- docs/src/uml-diagrams/arc42/runtime-view/policies/policy-startup-notification-contract.puml
resolves eclipse-tractusx/traceability-foss#596
> chore(docs): #596 rework policy store documentation

- frontend/src/app/modules/page/notifications/core/notification-helper.service.ts
- frontend/src/app/modules/page/notifications/detail/notification-detail.component.ts
resolves eclipse-tractusx/traceability-foss#616
> chore(feature): 616 - Cypress test fix.

- charts/connector/aasregistry/Chart.yaml
- charts/connector/aasregistry/values-dev.yaml
- charts/connector/aasregistry/values-e2e-a.yaml
- charts/connector/aasregistry/values-e2e-b.yaml
- charts/connector/aasregistry/values-int-a.yaml
- charts/connector/aasregistry/values-int-b.yaml
- charts/connector/aasregistry/values-test.yaml
- charts/connector/aasregistry/values.yaml
- charts/traceability-foss/charts/backend/Chart.yaml
resolves eclipse-tractusx/traceability-foss#636
> feature: #636 udpate registry from 0.3.22 to 0.4.9-RC2

- .github/argo/argo_config.sh
> bug: fix argo workflow

- charts/connector/aasregistry/Chart.yaml
- charts/connector/aasregistry/values-dev.yaml
- charts/connector/aasregistry/values-e2e-a.yaml
- charts/connector/aasregistry/values-e2e-b.yaml
- charts/connector/aasregistry/values-int-a.yaml
- charts/connector/aasregistry/values-int-b.yaml
- charts/connector/aasregistry/values-test.yaml
- charts/connector/aasregistry/values.yaml
- charts/traceability-foss/charts/backend/Chart.yaml
Reverts catenax-ng/tx-traceability-foss#1096
> Revert "feature: #636 udpate registry from 0.3.22 to 0.4.9-RC2"

- tx-backend/src/main/java/org/eclipse/tractusx/traceability/assets/infrastructure/base/irs/model/response/relationship/Aspect.java
- tx-backend/testdata/CX_Testdata_MessagingTest_v0.0.13.json
> bug: downgrade aspects because they are not provided by semantic hub

- frontend/src/app/modules/page/notifications/detail/edit/notification-edit.component.html
- frontend/src/app/modules/page/notifications/detail/edit/notification-edit.component.spec.ts
- frontend/src/app/modules/page/notifications/detail/edit/notification-edit.component.ts
- frontend/src/assets/locales/de/common.json
- frontend/src/assets/locales/en/common.json
resolves eclipse-tractusx/traceability-foss#623
> feature(notification): 623 implement feedback

- tx-backend/src/main/resources/db/migration/V22__add_asset_as_built_fk_to_tractionbatterycode.sql
resolves eclipse-tractusx/traceability-foss#828
> bug: #828 fix flyway scripts

- CHANGELOG.md
- charts/traceability-foss/Chart.yaml
resolves eclipse-tractusx/traceability-foss#778
> feature: #778 udpate edc version 0.7.0

- charts/connector/edc-provider/values-e2e-a.yaml
- charts/connector/edc-provider/values-e2e-b.yaml
- charts/connector/edc-provider/values-int-a.yaml
- charts/connector/edc-provider/values-int-b.yaml
- charts/connector/edc-provider/values-int-bmw.yaml
- charts/traceability-foss/values-base.yaml
- charts/traceability-foss/values-dev.yaml
- charts/traceability-foss/values-e2e-a.yaml
- charts/traceability-foss/values-e2e-b.yaml
- charts/traceability-foss/values-int-a.yaml
- charts/traceability-foss/values-int-b.yaml
- charts/traceability-foss/values-int-basf.yaml
- charts/traceability-foss/values-int-bmw.yaml
- charts/traceability-foss/values-test.yaml
resolves eclipse-tractusx/traceability-foss#778
> helm: #778 update values files

- CHANGELOG.md
- tx-backend/src/main/java/org/eclipse/tractusx/traceability/shelldescriptor/domain/service/DecentralRegistryServiceImpl.java
fixes https://github.com/eclipse-tractusx/traceability-foss/issues/945
> bug: revert digitalTwinType functionality

- CHANGELOG.md
- tx-backend/src/main/java/org/eclipse/tractusx/traceability/notification/domain/base/service/NotificationsEDCFacade.java
resolves eclipse-tractusx/traceability-foss#778
> chore(helm):778 adding counterPartyId to catalog request.

- pom.xml
- tx-backend/src/test/java/org/eclipse/tractusx/traceability/integration/notification/alert/ReadAlertsControllerIT.java
resolves eclipse-tractusx/traceability-foss#783
> chore(helm):783 update irs lib to release version

- tx-backend/src/main/java/org/eclipse/tractusx/traceability/notification/domain/notification/exception/NotificationSenderAndReceiverBPNEqualException.java
resolves eclipse-tractusx/traceability-foss#783
> chore(exception):783 update error message

- CHANGELOG.md
- COMPATIBILITY_MATRIX.md
- charts/traceability-foss/CHANGELOG.md
> chore(release): 11.0.1
